// <auto-generated />
namespace TrailAid.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class next31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next31));
        
        string IMigrationMetadata.Id
        {
            get { return "202011051422475_next31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
