// <auto-generated />
namespace TrailAid.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class next8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next8));
        
        string IMigrationMetadata.Id
        {
            get { return "202011031721292_next8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
